config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists do
    resources :bookmarks, only: [:create, :new]
    # Inside -> You need ID
  end
  resources :bookmarks, only: :destroy
  # Outisde -> Index show edit update destroy
end


# -> edit bookmark, I might understand parent and children relation

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6, message: "Heyy too short!" }
  validates :movie_id, uniqueness: { scope: :list_id, message: "It is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # before_destroy :check_bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true

  # private

  # def check_bookmarks
  #   if bookmarks.count > 0
  #     # errors.add_to_base("cannot delete movies while bookmarks exist")
  #     return false
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)

    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  #   @bookmark = Bookmark.find(params[:id])
  # end

  # def update
  #   @bookmark = Bookmark.find(params[:id])
  #   @bookmark.update(bookmarks_params)
  #   redirect_to list_path(@list)
  # end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    @list.save
    redirect_to lists_path
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(lists_params)
    redirect_to list_path(list)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end

  private

  def lists_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create your Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>

<%= f.submit "Submit Bookmark"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>edit article</h1>

<%= simple_form_for [@list] do |f| %>
<%= f.input :name %>

<%= f.submit "Submit review"%>
<% end %>

app/views/lists/index.html.erb
<div class="header">
  <h1>Lists</h1>
  <button type="button" class="create-button"><%= link_to "Create list",  new_list_path%></button>
  <form class="search-form" action="action_page.php">
    <input type="text" placeholder="" name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
</div>
<div class="banner">
  <%= image_tag "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" %>
</div>

<div class="cards">
    <% @lists.each do |list| %>
    <div class="card">
      <% if list.photo.key != nil  %>
        <%= cl_image_tag list.photo.key %>
      <% end %>
      List Name: <%= link_to list.name, list_path(list) %>
    </div>

    <% end %>
</div>
    <!-- app/views/articles/index.html.erb -->
    <%# <%= cl_image_tag("uctsw2xde7dyibfcy7mu",
          width: 400, height: 300, crop: :fill) %>
    <!-- for face detection -->
    <%# <%= cl_image_tag("ditvkt4utys8ei9fgezl",
          width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/lists/new.html.erb
<h1>New article</h1>

<%= simple_form_for [@list] do |f| %>
<%= f.input :name %>

<%= f.submit "Submit review"%>
<% end %>

app/views/lists/show.html.erb
<div>
  <h1>List name: <%= @list.name %></h1>
  <p><%= link_to 'Edit your list', edit_list_path(@list.id) %></p>
  <p><%= link_to 'Delete', list_path(@list.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
  <p><%= link_to "Create bookmarks",  new_list_bookmark_path(@list.id) %></p>
</div>

<div>
  <% if @list.photo.key != nil  %>
    <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
    <div class="card-category"
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
      Cool article
    </div>
  <% end %>
</div>

<div>
  <% @list.bookmarks.each do |bookmark| %>
    <p><%= bookmark.movie.title %></p>
    <p><%= bookmark.movie.overview %></p>
    <p><%= bookmark.movie.rating %></p>
    <%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want delete ?"} %>
  <% end %>
</div>
<%# <%= link_to "delete", bookmark_path(@bookmark.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want delete ?"} %>
<p><%= link_to 'Go Back', lists_path %></p>